services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: bugdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./templates:/app/templates
    environment:
      DB_HOST: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: bugdb
    depends_on:
      - db

volumes:
  db_data:

